#ifndef THOUGHT_CHAINPARAMSSEEDS_H
#define THOUGHT_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the thought network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside a IPv6 address accordingly.
 */
static SeedSpec6 pnSeed6_main[] = {

};

static SeedSpec6 pnSeed6_test[] = {
    {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,0x34,0x1a,0x0d,0x2c}, 11618}
};
#endif // THOUGHT_CHAINPARAMSSEEDS_H
